workflows:
  android-release:
    name: Android Release APK
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.multimarketpro"  # ← Cambiá esto por tu package real si es diferente
      node: latest
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: main
    scripts:
      - name: Install dependencies
        script: |
          yarn install --frozen-lockfile || npm ci
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients:
          - tuemail@gmail.com   # opcional, te llega por mail también
