workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - multimarket_pro_key
      vars:
        PACKAGE_NAME: com.jgvsolutions.multimarketpro
        APP_NAME: MultiMarket-Pro
    triggers:
      - push
        branches:
          - main
    scripts:
      - name: Build Flutter APK
        script: |
          flutter pub get
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: true
